/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivitiesTable: typeof import('./src/components/ActivitiesTable.vue')['default']
    ConfirmationDialog: typeof import('./src/components/ConfirmationDialog.vue')['default']
    DrivesTable: typeof import('./src/components/DrivesTable.vue')['default']
    FetchingAutocomplete: typeof import('./src/components/FetchingAutocomplete.vue')['default']
    HidingButton: typeof import('./src/components/HidingButton.vue')['default']
    OrganizationAddDialog: typeof import('./src/components/OrganizationAddDialog.vue')['default']
    OrganizationAddForm: typeof import('./src/components/OrganizationAddForm.vue')['default']
    OrganizationEditData: typeof import('./src/components/OrganizationEditData.vue')['default']
    OrganizationEditDialog: typeof import('./src/components/OrganizationEditDialog.vue')['default']
    OrganizationEditLogo: typeof import('./src/components/OrganizationEditLogo.vue')['default']
    OrganizationFilter: typeof import('./src/components/OrganizationFilter.vue')['default']
    PaginatedAutocomplete: typeof import('./src/components/PaginatedAutocomplete.vue')['default']
    PasswordInput: typeof import('./src/components/PasswordInput.vue')['default']
    PasswordStrength: typeof import('./src/components/PasswordStrength.vue')['default']
    ProfileChange: typeof import('./src/components/ProfileChange.vue')['default']
    ProfileChangeData: typeof import('./src/components/ProfileChangeData.vue')['default']
    ProfileChangePassword: typeof import('./src/components/ProfileChangePassword.vue')['default']
    ProfileData: typeof import('./src/components/ProfileData.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheDialog: typeof import('./src/components/TheDialog.vue')['default']
    TheDialogCard: typeof import('./src/components/TheDialogCard.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheLogoutButton: typeof import('./src/components/TheLogoutButton.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
    TheSnackbar: typeof import('./src/components/TheSnackbar.vue')['default']
    UserAddDialog: typeof import('./src/components/UserAddDialog.vue')['default']
    UserAddForm: typeof import('./src/components/UserAddForm.vue')['default']
    UserEditDialog: typeof import('./src/components/UserEditDialog.vue')['default']
    UserEditForm: typeof import('./src/components/UserEditForm.vue')['default']
    UsersFilter: typeof import('./src/components/UsersFilter.vue')['default']
    VirtualMachineAddDialog: typeof import('./src/components/VirtualMachineAddDialog.vue')['default']
    VirtualMachineAddForm: typeof import('./src/components/VirtualMachineAddForm.vue')['default']
    VirtualMachineFilter: typeof import('./src/components/VirtualMachineFilter.vue')['default']
  }
}
